Type=StaticCode
Version=5.8
ModulesStructureVersion=1
B4A=true
@EndOfDesignText@
'Code module
'Subs in this code module will be accessible from all modules.
Sub Process_Globals
	'These global variables will be declared once when the application starts.
	'These variables can be accessed from all modules.
	Dim Q As String
	Dim C As Cursor
	Dim record As Map

End Sub

Sub DatabaseSetup
	SystemsTable
	StationsTable
	StockMarketTable
	FactionsTable
	GalacticPricesTable
	CommodityGroupTable
	CommoditiesTable
	RarecommoditiesTable
	StockTypesTable
	StockLevelsTable
	GovernmentsTable
	AllegianceTable
	EconomiesTable
	StationTypesTable
	PopulationTable
	LocationTable
	MaxLYTradeDistanceTable
	TempTables
End Sub

Sub SystemsTable
	If SQLUtils.TableExists(Starter.SQLExec,"Systems") = False Then
		' Create Systems Table
		Q = "CREATE TABLE Systems(SystemName TEXT PRIMARY KEY, GovDesc TEXT, AllegDesc TEXT, EconomyID INTEGER, SpaceX REAL, SpaceY REAL, SpaceZ REAL, LYfromCurrent REAL, ExactLocation INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"Systems","SysName","SystemName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"Systems","LightYears","LYfromCurrent",False)
		' Default Data Load
		Q = "SELECT * FROM Systems"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("GovDesc", "")
			record.Put("AllegDesc", "")
			record.Put("EconomyID", 0)
			record.Put("LYfromCurrent", 0)
			record.Put("ExactLocation", 1)
	
			record.Put("SystemName", "39 Tauri")
			record.Put("SpaceX", -7.3125)
			record.Put("SpaceY", -20.28125)
			record.Put("SpaceZ", -50.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "47 Ceti")
			record.Put("SpaceX", -14.125)
			record.Put("SpaceY", -116.96875)
			record.Put("SpaceZ", -32.53125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Aegaeon")
			record.Put("SpaceX", 46.90625)
			record.Put("SpaceY", 23.625)
			record.Put("SpaceZ", -59.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Aerial")
			record.Put("SpaceX", 100.75)
			record.Put("SpaceY", -102.625)
			record.Put("SpaceZ", 8.40625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Alacarakmo")
			record.Put("SpaceX", -32.40625)
			record.Put("SpaceY", 169.53125)
			record.Put("SpaceZ", -49.4375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Alpha Centauri")
			record.Put("SpaceX", 3.03125)
			record.Put("SpaceY", -0.09375)
			record.Put("SpaceZ", 3.15625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Altair")
			record.Put("SpaceX", -12.3125)
			record.Put("SpaceY", -2.75)
			record.Put("SpaceZ", 11.0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Alya")
			record.Put("SpaceX", -77.28125)
			record.Put("SpaceY", -57.4375)
			record.Put("SpaceZ", 30.53125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Anduliga")
			record.Put("SpaceX", 124.625)
			record.Put("SpaceY", 2.5)
			record.Put("SpaceZ", 61.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Any Na")
			record.Put("SpaceX", 125.65625)
			record.Put("SpaceY", -1.71875)
			record.Put("SpaceZ", 14.09375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Arouca")
			record.Put("SpaceX", 104.96875)
			record.Put("SpaceY", -6.53125)
			record.Put("SpaceZ", -4.40625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "AZ Cancri")
			record.Put("SpaceX", 19.65625)
			record.Put("SpaceY", 26.84375)
			record.Put("SpaceZ", -38.09375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Baltah'sine")
			record.Put("SpaceX", 85.15625)
			record.Put("SpaceY", -56.3125)
			record.Put("SpaceZ", 40.34375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Banki")
			record.Put("SpaceX", 49.53125)
			record.Put("SpaceY", 15.75)
			record.Put("SpaceZ", -91.71875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Bast")
			record.Put("SpaceX", -36.46875)
			record.Put("SpaceY", 16.15625)
			record.Put("SpaceZ", -34.9375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Belalans")
			record.Put("SpaceX", 81.625)
			record.Put("SpaceY", -94.875)
			record.Put("SpaceZ", -58.5625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "CD-75 661")
			record.Put("SpaceX", 67.875)
			record.Put("SpaceY", -21.5)
			record.Put("SpaceZ", 51.15625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Cherbones")
			record.Put("SpaceX", 5.1875)
			record.Put("SpaceY", 84.53125)
			record.Put("SpaceZ", -16.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Chi Eridani")
			record.Put("SpaceX", 26.28125)
			record.Put("SpaceY", -51.75)
			record.Put("SpaceZ", 4.625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Coquim")
			record.Put("SpaceX", 20.75)
			record.Put("SpaceY", -82.25)
			record.Put("SpaceZ", 33.59375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Damna")
			record.Put("SpaceX", -40.53125)
			record.Put("SpaceY", 4.375)
			record.Put("SpaceZ", -124.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Dea Motrona")
			record.Put("SpaceX", -12.15625)
			record.Put("SpaceY", 62.625)
			record.Put("SpaceZ", 29.71875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Delta Phoenicis")
			record.Put("SpaceX", 53.90625)
			record.Put("SpaceY", -130.6875)
			record.Put("SpaceZ", 14.65625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Deuringas")
			record.Put("SpaceX", 137.3125)
			record.Put("SpaceY", 3.84375)
			record.Put("SpaceZ", -35.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Diso")
			record.Put("SpaceX", 72.15625)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 70.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Eleu")
			record.Put("SpaceX", -29.65625)
			record.Put("SpaceY", 32.6875)
			record.Put("SpaceZ", 104.84375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Epsilon Indi")
			record.Put("SpaceX", 3.125)
			record.Put("SpaceY", -8.875)
			record.Put("SpaceZ", 7.125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Eranin")
			record.Put("SpaceX", -22.84375)
			record.Put("SpaceY", 36.53125)
			record.Put("SpaceZ", -1.1875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Eshu")
			record.Put("SpaceX", 120.78125)
			record.Put("SpaceY", -247.1875)
			record.Put("SpaceZ", -16.4375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Esuseku")
			record.Put("SpaceX", -107.875)
			record.Put("SpaceY", 29.5625)
			record.Put("SpaceZ", -20.9375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Ethgreze")
			record.Put("SpaceX", -30.03125)
			record.Put("SpaceY", 72.34375)
			record.Put("SpaceZ", -23.8125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Fujin")
			record.Put("SpaceX", -6.03125)
			record.Put("SpaceY", -30.375)
			record.Put("SpaceZ", -59.03125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Geawen")
			record.Put("SpaceX", 22.5)
			record.Put("SpaceY", 23.78125)
			record.Put("SpaceZ", 171.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "George Pantazis")
			record.Put("SpaceX", -12.09375)
			record.Put("SpaceY", -16.0)
			record.Put("SpaceZ", -14.21875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Geras")
			record.Put("SpaceX", -7.03125)
			record.Put("SpaceY", -12.875)
			record.Put("SpaceZ", -56.375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Goman")
			record.Put("SpaceX", 151.875)
			record.Put("SpaceY", -173.78125)
			record.Put("SpaceZ", 25.28125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Haiden")
			record.Put("SpaceX", -142.03125)
			record.Put("SpaceY", -13.34375)
			record.Put("SpaceZ", -43.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Havasupai")
			record.Put("SpaceX", -88.75)
			record.Put("SpaceY", -76.75)
			record.Put("SpaceZ", -39.625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Hecate")
			record.Put("SpaceX", -56.0)
			record.Put("SpaceY", -25.125)
			record.Put("SpaceZ", -44.28125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Heike")
			record.Put("SpaceX", -76.96875)
			record.Put("SpaceY", 71.90625)
			record.Put("SpaceZ", 69.1875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Helvetitj")
			record.Put("SpaceX", -23.1875)
			record.Put("SpaceY", 80.03125)
			record.Put("SpaceZ", 61.84375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HIP 10175")
			record.Put("SpaceX", -45.78125)
			record.Put("SpaceY", -93.5)
			record.Put("SpaceZ", -83.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HIP 110620")
			record.Put("SpaceX", -78.1875)
			record.Put("SpaceY", -132.125)
			record.Put("SpaceZ", 63.5625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HIP 41181")
			record.Put("SpaceX", -8.15625)
			record.Put("SpaceY", 74.8125)
			record.Put("SpaceZ", -105.125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HIP 59533")
			record.Put("SpaceX", 122.96875)
			record.Put("SpaceY", -9.0625)
			record.Put("SpaceZ", 69.0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HIP 80364")
			record.Put("SpaceX", -101.59375)
			record.Put("SpaceY", 93.78125)
			record.Put("SpaceZ", 9.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Holva")
			record.Put("SpaceX", 58.6875)
			record.Put("SpaceY", -170.96875)
			record.Put("SpaceZ", -41.96875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "HR 7221")
			record.Put("SpaceX", 58.53125)
			record.Put("SpaceY", -55.8125)
			record.Put("SpaceZ", 91.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Irukama")
			record.Put("SpaceX", 140.71875)
			record.Put("SpaceY", -96.96875)
			record.Put("SpaceZ", 67.78125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Jaradharre")
			record.Put("SpaceX", 39.53125)
			record.Put("SpaceY", 21.28125)
			record.Put("SpaceZ", 56.625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Jaroua")
			record.Put("SpaceX", 157.53125)
			record.Put("SpaceY", -110.53125)
			record.Put("SpaceZ", 28.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Jotun")
			record.Put("SpaceX", -11.03125)
			record.Put("SpaceY", -79.21875)
			record.Put("SpaceZ", -92.3125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kachirigin")
			record.Put("SpaceX", -105.375)
			record.Put("SpaceY", -73.34375)
			record.Put("SpaceZ", 27.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kamitra")
			record.Put("SpaceX", 5.53125)
			record.Put("SpaceY", -183.40625)
			record.Put("SpaceZ", 63.84375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kamorin")
			record.Put("SpaceX", -123.875)
			record.Put("SpaceY", -81.59375)
			record.Put("SpaceZ", 45.1875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kappa Fornacis")
			record.Put("SpaceX", 12.46875)
			record.Put("SpaceY", -66.71875)
			record.Put("SpaceZ", -22.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Karetii")
			record.Put("SpaceX", -125.59375)
			record.Put("SpaceY", 44.03125)
			record.Put("SpaceZ", 78.40625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Karsuki Ti")
			record.Put("SpaceX", 134.03125)
			record.Put("SpaceY", -163.59375)
			record.Put("SpaceZ", 71.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kinago")
			record.Put("SpaceX", -67.40625)
			record.Put("SpaceY", -7.40625)
			record.Put("SpaceZ", 150.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Kongga")
			record.Put("SpaceX", -67.40625)
			record.Put("SpaceY", -7.40625)
			record.Put("SpaceZ", 150.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Korro Kung")
			record.Put("SpaceX", 81.03125)
			record.Put("SpaceY", 52.84375)
			record.Put("SpaceZ", 31.5)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Lave")
			record.Put("SpaceX", 75.75)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 70.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "LDS 883")
			record.Put("SpaceX", -28.71875)
			record.Put("SpaceY", -35.71875)
			record.Put("SpaceZ", -61.4375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Leesti")
			record.Put("SpaceX", 72.75)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 68.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "LFT 1421")
			record.Put("SpaceX", -45.46875)
			record.Put("SpaceY", 18.5625)
			record.Put("SpaceZ", 12.59375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "LP 375-25")
			record.Put("SpaceX", 9.53125)
			record.Put("SpaceY", 59.3125)
			record.Put("SpaceZ", -13.21875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Mechucos")
			record.Put("SpaceX", 67.03125)
			record.Put("SpaceY", 39.59375)
			record.Put("SpaceZ", -70.09375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Medb")
			record.Put("SpaceX", 12.78125)
			record.Put("SpaceY", 4.8125)
			record.Put("SpaceZ", 39.34375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Mokojing")
			record.Put("SpaceX", 73.4375)
			record.Put("SpaceY", 58.34375)
			record.Put("SpaceZ", -0.21875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Momus Reach")
			record.Put("SpaceX", -34.9375)
			record.Put("SpaceY", -44.15625)
			record.Put("SpaceZ", -77.34375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Mukusubii")
			record.Put("SpaceX", -147.46875)
			record.Put("SpaceY", -64.125)
			record.Put("SpaceZ", 46.09375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Mulachi")
			record.Put("SpaceX", 6.25)
			record.Put("SpaceY", -5.78125)
			record.Put("SpaceZ", 35.9375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Neritus")
			record.Put("SpaceX", 75.4375)
			record.Put("SpaceY", 2.625)
			record.Put("SpaceZ", -30.875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Ngadandari")
			record.Put("SpaceX", 62.75)
			record.Put("SpaceY", -74.1875)
			record.Put("SpaceZ", 109.5)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Nguna")
			record.Put("SpaceX", -122.78125)
			record.Put("SpaceY", -102.53125)
			record.Put("SpaceZ", -22.5625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Ngurii")
			record.Put("SpaceX", 169.5)
			record.Put("SpaceY", -42.34375)
			record.Put("SpaceZ", 87.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Njangari")
			record.Put("SpaceX", 8.875)
			record.Put("SpaceY", -205.4375)
			record.Put("SpaceZ", 64.375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Ochoeng")
			record.Put("SpaceX", -139.0625)
			record.Put("SpaceY", -2.3125)
			record.Put("SpaceZ", -6.65625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Orrere")
			record.Put("SpaceX", 68.84375)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 76.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Phiagre")
			record.Put("SpaceX", 44.28125)
			record.Put("SpaceY", -82.96875)
			record.Put("SpaceZ", 52.5)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Quechua")
			record.Put("SpaceX", 52.09375)
			record.Put("SpaceY", -112.09375)
			record.Put("SpaceZ", -40.78125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Rajukru")
			record.Put("SpaceX", -96.9375)
			record.Put("SpaceY", 143.4375)
			record.Put("SpaceZ", 4.625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Rapa Bao")
			record.Put("SpaceX", 94.15625)
			record.Put("SpaceY", -167.375)
			record.Put("SpaceZ", -23.1875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Rusani")
			record.Put("SpaceX", -64.75)
			record.Put("SpaceY", 57.21875)
			record.Put("SpaceZ", -82.625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Sanuma")
			record.Put("SpaceX", 153.4375)
			record.Put("SpaceY", 61.4375)
			record.Put("SpaceZ", 79.03125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Shinrarta Dezhra")
			record.Put("SpaceX", 55.71875)
			record.Put("SpaceY", 17.59375)
			record.Put("SpaceZ", 27.15625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Sol")
			record.Put("SpaceX", 0)
			record.Put("SpaceY", 0)
			record.Put("SpaceZ", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Sothis")
			record.Put("SpaceX", -352.78125)
			record.Put("SpaceY", 10.5)
			record.Put("SpaceZ", -346.34375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Tanmark")
			record.Put("SpaceX", 1.6875)
			record.Put("SpaceY", -77.875)
			record.Put("SpaceZ", -30.09375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Tarach Tor")
			record.Put("SpaceX", -13.125)
			record.Put("SpaceY", -81.0)
			record.Put("SpaceZ", -20.28125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Terra Mater")
			record.Put("SpaceX", -49.75)
			record.Put("SpaceY", -19.03125)
			record.Put("SpaceZ", -45.0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Thrutis")
			record.Put("SpaceX", -90.6875)
			record.Put("SpaceY", 8.125)
			record.Put("SpaceZ", -79.53125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Tiolce")
			record.Put("SpaceX", 10.5)
			record.Put("SpaceY", -34.78125)
			record.Put("SpaceZ", 25.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Toxandji")
			record.Put("SpaceX", 155.09375)
			record.Put("SpaceY", -12.40625)
			record.Put("SpaceZ", 61.0625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Uszaa")
			record.Put("SpaceX", 68.84375)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 74.75)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Utgaroar")
			record.Put("SpaceX", -0.15625)
			record.Put("SpaceY", -102.75)
			record.Put("SpaceZ", -5.5625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Uzumoku")
			record.Put("SpaceX", -95.21875)
			record.Put("SpaceY", 9.875)
			record.Put("SpaceZ", -74.125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "V1090 Herculis")
			record.Put("SpaceX", -44.9375)
			record.Put("SpaceY", 36.9375)
			record.Put("SpaceZ", 13.46875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Vanayequi")
			record.Put("SpaceX", -88.5)
			record.Put("SpaceY", -12.3125)
			record.Put("SpaceZ", 98.84375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Vega")
			record.Put("SpaceX", -21.90625)
			record.Put("SpaceY", 8.125)
			record.Put("SpaceZ", 9.0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Vidavanta")
			record.Put("SpaceX", -50.9375)
			record.Put("SpaceY", 90.21875)
			record.Put("SpaceZ", 65.8125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Volkhab")
			record.Put("SpaceX", 36.53125)
			record.Put("SpaceY", 100.0625)
			record.Put("SpaceZ", -135.71875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Wheemete")
			record.Put("SpaceX", 145.125)
			record.Put("SpaceY", -140.0625)
			record.Put("SpaceZ", 131.96875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Witchhaul")
			record.Put("SpaceX", -13.25)
			record.Put("SpaceY", -52.0625)
			record.Put("SpaceZ", -65.875)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Wolf 1301")
			record.Put("SpaceX", -15.4375)
			record.Put("SpaceY", -34.6875)
			record.Put("SpaceZ", -79.40625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Wulpa")
			record.Put("SpaceX", -126.09375)
			record.Put("SpaceY", -83.09375)
			record.Put("SpaceZ", -85.5625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Wuthielo Ku")
			record.Put("SpaceX", 68.3125)
			record.Put("SpaceY", -190.03125)
			record.Put("SpaceZ", 12.375)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Xihe")
			record.Put("SpaceX", -19.8125)
			record.Put("SpaceY", -35.375)
			record.Put("SpaceZ", 34.0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Yaso Kondi")
			record.Put("SpaceX", 4.9375)
			record.Put("SpaceY", -175.90625)
			record.Put("SpaceZ", -0.90625)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Zaonce")
			record.Put("SpaceX", 80.75)
			record.Put("SpaceY", 48.75)
			record.Put("SpaceZ", 69.25)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			record.Put("SystemName", "Zeessze")
			record.Put("SpaceX", -19.8125)
			record.Put("SpaceY", -3.25)
			record.Put("SpaceZ", -14.28125)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Systems",record)
			
		End If
	End If
End Sub

Sub StationsTable
	If SQLUtils.TableExists(Starter.SQLExec,"Stations") = False Then
		' Create Stations Table
		Q = "CREATE TABLE Stations(StationName TEXT PRIMARY KEY, SystemName TEXT, StatTypeDesc TEXT, PopulationSize TEXT, EconomyNum INTEGER, BlackMarketAvailable INTEGER, ArrivalPoint REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create indices
		SQLUtils.CreateIndex(Starter.SQLExec,"Stations","StatName","StationName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"Stations","SysName","SystemName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"Stations","SysStat","SystemName,StationName",False)
	End If
End Sub

Sub StockMarketTable
	If SQLUtils.TableExists(Starter.SQLExec,"StockMarket") = False Then
		' Create StockMarket Data Table
		Q = "CREATE TABLE StockMarket(RecordID INTEGER PRIMARY KEY, SystemName TEXT, StationName TEXT, ComGrpDesc TEXT, CommodDesc TEXT, StockTypeDesc TEXT, StockLevelRank INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"StockMarket","SysStat","SystemName,StationName",False)
	End If
End Sub	

Sub FactionsTable
	If SQLUtils.TableExists(Starter.SQLExec,"Factions") = False Then
		' Create Factions Data Table
		Q = "CREATE TABLE Factions(RecordID INTEGER PRIMARY KEY, FactionName TEXT , SystemName TEXT)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"Factions","SysFact","SystemName,FactionName",False)
	End If
End Sub

Sub GalacticPricesTable
	If SQLUtils.TableExists(Starter.SQLExec,"GalacticPrices") = False Then
		' Create GalacticPrice Data Table
		Q = "CREATE TABLE GalacticPrices(CommodDesc TEXT PRIMARY KEY, GP REAL, HighHP REAL, LowHP REAL, AvgHP REAL, HighMP REAL, LowMP REAL, AvgMP REAL, HighLP REAL, LowLP REAL, AvgLP REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
End Sub

Sub CommodityGroupTable
	If SQLUtils.TableExists(Starter.SQLExec,"CommodityGroups") = False Then
		' Create Commodity Groups Table
		Q = "CREATE TABLE CommodityGroups(ComGrpDesc TEXT PRIMARY KEY)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Default Data Load
		Q = "SELECT * FROM CommodityGroups"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("ComGrpDesc", "Chemicals")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Consumer Items")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Foods")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Industrial Materials")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Legal Drugs")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Machinery")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Medicines")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Metals")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Minerals")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Salvage")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Slavery")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Technology")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Textiles")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Waste")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Weapons")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
			record.Put("ComGrpDesc", "Unknown")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"CommodityGroups",record)
		End If
	End If
End Sub

Sub CommoditiesTable
	If SQLUtils.TableExists(Starter.SQLExec,"Commodities") = False Then
		' Create Commodities Table
		Q = "CREATE TABLE Commodities(CommodDesc TEXT PRIMARY KEY, ComGrpDesc TEXT, Trading INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Default Data Load
		Q = "SELECT * FROM Commodities"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("Trading", 1) 'Currently available to Trade

			#Region Chemicals
			record.Put("ComGrpDesc", "Chemicals") 'Chemicals
			record.Put("CommodDesc", "Explosives")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Hydrogen Fuel")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Mineral Oil")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Nerve Agents")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Pesticides")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Surface Stabilisers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Synthetic Reagents")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Consumer Items
			record.Put("ComGrpDesc", "Consumer Items") 'Consumer Items
			record.Put("CommodDesc", "Clothing")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Consumer Technology")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Domestic Appliances")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Evacuation Shelter")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Foods
			record.Put("ComGrpDesc", "Foods") 'Foods
			record.Put("CommodDesc", "Algae")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Animal Meat")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Coffee")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Fish")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Food Cartridges")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Fruit And Vegetables")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Grain")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Synthetic Meat")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Tea")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Industrial Meterials
			record.Put("ComGrpDesc", "Industrial Materials") 'Industrial Materials
			record.Put("CommodDesc", "Ceramic Composites")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Polymers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Meta-Alloys")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Semiconductors")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Superconductors")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Legal Drugs
			record.Put("ComGrpDesc", "Legal Drugs") 'Legal Drugs
			record.Put("CommodDesc", "Beer")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Bootleg Liquor")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Liquor")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Narcotics")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Tobacco")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Wine")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Machinery
			record.Put("ComGrpDesc", "Machinery") 'Machinery
			record.Put("CommodDesc", "Atmospheric Processors")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Building Fabricators")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Crop Harvesters")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Geological Equipment")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Marine Equipment")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Microbial Furnaces")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Mineral Extractors")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Power Generators")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Skimmer Components")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Thermal Cooling Units")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Water Purifiers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Medicines
			record.Put("ComGrpDesc", "Medicines") 'Medicines
			record.Put("CommodDesc", "Agri-Medicines")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Basic Medicines")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Combat Stabilisers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Performance Enhancers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Progenitor Cells")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Metals
			record.Put("ComGrpDesc", "Metals") 'Metals
			record.Put("CommodDesc", "Aluminium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Beryillium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Bismuth")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Cobalt")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Copper")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Gallium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Gold")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Indium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Lanthanum")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Lithium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Osmium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Palladium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Platinum")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Silver")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Tantalum")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Thallium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Thorium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Titanium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Uranium")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Minerals
			record.Put("ComGrpDesc", "Minerals") 'Minerals
			record.Put("CommodDesc", "Bauxite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Bertrandite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Coltan")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Cryolite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Gallite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Goslarite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Indite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Lepidolite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Moissanite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Painite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Pyrophyllite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Rutile")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Uraninite")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Salvage
			record.Put("ComGrpDesc", "Salvage") 'Salvage
			record.Put("CommodDesc", "SAP 8 Core Container")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Slavery
			record.Put("ComGrpDesc", "Slavery") 'Slavery
			record.Put("CommodDesc", "Imperial Slaves")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Slaves")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Technology
			record.Put("ComGrpDesc", "Technology") 'Technology
			record.Put("CommodDesc", "Advanced Catalysers")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Animal Monitors")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Aquaponic Systems")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Auto-Fabricators")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Bioreducing Lichen")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Computer Components")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "H.E. Suits")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Land Enrichment Systems")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Muon Imager")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Resonating Separators")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Robotics")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Structural Regulators")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Textiles
			record.Put("ComGrpDesc", "Textiles") 'Textiles
			record.Put("CommodDesc", "Leather")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Natural Fabrics")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Synthetic Fabrics")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Waste
			record.Put("ComGrpDesc", "Waste") 'Waste
			record.Put("CommodDesc", "Biowaste")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Chemical Waste")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Scrap")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
			#Region Weapons
			record.Put("ComGrpDesc", "Weapons") 'Weapons
			record.Put("CommodDesc", "Battle Weapons")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Landmines")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Non-Lethal Weapons")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Personal Weapons")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			record.Put("CommodDesc", "Reactive Armour")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Commodities",record)
			#End Region
		End If
	End If
End Sub

Sub RarecommoditiesTable
	If SQLUtils.TableExists(Starter.SQLExec,"RareCommodities") = False Then
		' Create RareCommodities Table
		Q = "CREATE TABLE RareCommodities(RareDesc TEXT PRIMARY KEY, ComGrpDesc TEXT, RareSystem TEXT, RareStation TEXT, Allowance INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		
		Q = "SELECT * FROM RareCommodities"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize

			#Region Chemicals
			#End Region
			#Region Comsumer Items
			record.Put("ComGrpDesc", "Consumer Items") 'Consumer Items
			record.Put("RareDesc", "Leathery Eggs")
			record.Put("RareSystem", "Zaonce")
			record.Put("RareStation", "Ridley Scott")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Tauri Chimes")
			record.Put("RareSystem", "39 Tauri")
			record.Put("RareStation", "Porta")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Altairian Skin")
			record.Put("RareSystem", "Altair")
			record.Put("RareStation", "Solo Orbiter")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Zeessze Ant Grub Glue")
			record.Put("RareSystem", "Zeessze")
			record.Put("RareStation", "Nicollier Hanger")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Anduliga Fire Works")
			record.Put("RareSystem", "Anduliga")
			record.Put("RareStation", "Celsius Estate")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Alacarakmo Skin Art")
			record.Put("RareSystem", "Alacarakmo")
			record.Put("RareStation", "Weyl Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Momus Bog Spaniel")
			record.Put("RareSystem", "Momus Reach")
			record.Put("RareStation", "Tartarus Point")
			record.Put("Allowance", 4)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Foods
			record.Put("ComGrpDesc", "Foods") 'Foods
			record.Put("RareDesc", "Diso Ma Corn")
			record.Put("RareSystem", "Diso")
			record.Put("RareStation", "Shifnalport")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Azure Milk")
			record.Put("RareSystem", "Leesti")
			record.Put("RareStation", "George Lucas")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Orrerian Vicious Brew")
			record.Put("RareSystem", "Orrere")
			record.Put("RareStation", "Sharon Lee Free Market")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Tanmark Tranquil Tea")
			record.Put("RareSystem", "Tanmark")
			record.Put("RareStation", "Cassie-L-Peia")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Aepyornis Egg")
			record.Put("RareSystem", "47 Ceti")
			record.Put("RareStation", "Glushko Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Ceti Rabbits")
			record.Put("RareSystem", "47 Ceti")
			record.Put("RareStation", "Kaufmanis Hub")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Eden Apples of Aerial")
			record.Put("RareSystem", "Aerial")
			record.Put("RareStation", "Andrade Legacy")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Any Na Coffee")
			record.Put("RareSystem", "Any Na")
			record.Put("RareStation", "Libby Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Arouca Conventula Sweets")
			record.Put("RareSystem", "Arouca")
			record.Put("RareStation", "Shipton Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Chi Eridani Marine Paste")
			record.Put("RareSystem", "Chi Eridani")
			record.Put("RareStation", "Steve Masters")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Baltah'sine Vacuum Krill")
			record.Put("RareSystem", "Baltah'sine")
			record.Put("RareStation", "Baltha'sine Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "CD-75 Kitten Brand Coffee")
			record.Put("RareSystem", "CD-75 661")
			record.Put("RareStation", "Kirk Dock")
			record.Put("Allowance", 2)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Coquim Spongiform Victuals")
			record.Put("RareSystem", "Coquim")
			record.Put("RareStation", "Hirayama Installation")
			record.Put("Allowance", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "HIP 10175 Bush Meat")
			record.Put("RareSystem", "HIP 10175")
			record.Put("RareStation", "Stefanyshyn-Piper Station")
			record.Put("Allowance", 13)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Witchhaul Kobe Beef")
			record.Put("RareSystem", "Witchhaul")
			record.Put("RareStation", "Hornby Terminal")
			record.Put("Allowance", 9)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Industrial Meterials
			#End Region
			#Region Legal Drugs
			record.Put("ComGrpDesc", "Legal Drugs") 'Legal Drugs
			record.Put("RareDesc", "Lavian Brandy")
			record.Put("RareSystem", "Lave")
			record.Put("RareStation", "Lave Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Leestian Evil Juice")
			record.Put("RareSystem", "Leesti")
			record.Put("RareStation", "George Lucas")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Tarach Spice")
			record.Put("RareSystem", "Tarach Tor")
			record.Put("RareStation", "Tranquillity")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Chateau De Aegaeon")
			record.Put("RareSystem", "Aegaeon")
			record.Put("RareStation", "Schweickart Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Centauri Mega Gin")
			record.Put("RareSystem", "Alpha Centauri")
			record.Put("RareStation", "Hutton Oribtal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Bast Snake Gin")
			record.Put("RareSystem", "Bast")
			record.Put("RareStation", "Hart Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Gerasian Gueuze Beer")
			record.Put("RareSystem", "Geras")
			record.Put("RareStation", "Yurchikhin Port")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Machinery
			#End Region
			#Region Medicines
			record.Put("ComGrpDesc", "Medicines") 'Medicines
			record.Put("RareDesc", "The Waters of Shintara")
			record.Put("RareSystem", "Shinrarta Dezhra")
			record.Put("RareStation", "Jameson Memorial")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Alya Body Soap")
			record.Put("RareSystem", "Alya")
			record.Put("RareStation", "Malaspina Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Metals
			record.Put("ComGrpDesc", "Metals") 'Metals
			record.Put("RareDesc", "Sothis Crystalline Gold")
			record.Put("RareSystem", "Sothis")
			record.Put("RareStation", "Newholm Station")
			record.Put("Allowance", 12)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Cherbones Blood Crystals")
			record.Put("RareSystem", "Cherbones")
			record.Put("RareStation", "Chalker Landing")
			record.Put("Allowance", 3)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Minerals
			#End Region
			#Region Salvage
			#End Region
			#Region Slavery
			#End Region
			#Region Technology
			record.Put("ComGrpDesc", "Technology") 'Technology
			record.Put("RareDesc", "Az Cancri Formula 42")
			record.Put("RareSystem", "AZ Cancri")
			record.Put("RareStation", "Fisher Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Textiles
			record.Put("ComGrpDesc", "Textiles") 'Textiles
			record.Put("RareDesc", "Banki Amphibious Leather")
			record.Put("RareSystem", "Banki")
			record.Put("RareStation", "Antonio De Andrade Vista")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Damna Carapaces")
			record.Put("RareSystem", "Damna")
			record.Put("RareStation", "Nemere Market")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Belalans Ray Leather")
			record.Put("RareSystem", "Belalans")
			record.Put("RareStation", "Boscovich Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Chameleon Cloth")
			record.Put("RareSystem", "LDS 883")
			record.Put("RareStation", "Smith Reserve")
			record.Put("Allowance", 7)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			#End Region
			#Region Waste
			#End Region
			#Region Weapons
			#End Region
			
			
			record.Put("ComGrpDesc", "Not Found") 'Not Found when visited
			record.Put("RareDesc", "Wolf Fesh")
			record.Put("RareSystem", "Wolf 1301")
			record.Put("RareStation", "Saunders's Dive")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)


			record.Put("ComGrpDesc", "Unknown") 'Unknown
			record.Put("RareDesc", "Motrona Experience Jelly")
			record.Put("RareSystem", "Dea Motrona")
			record.Put("RareStation", "Pinzon Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Delta Phoenicis Palms")
			record.Put("RareSystem", "Delta Phoenicis")
			record.Put("RareStation", "Trading Post")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Deuringas Truffles")
			record.Put("RareSystem", "Deuringas")
			record.Put("RareStation", "Shukor Hub")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Eleu Thermals")
			record.Put("RareSystem", "Eleu")
			record.Put("RareStation", "Finney Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Indi Bourbon")
			record.Put("RareSystem", "Epsilon Indi")
			record.Put("RareStation", "Mansfield Orbiter")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Eranin Pearl Whiskey")
			record.Put("RareSystem", "Eranin")
			record.Put("RareStation", "Azeban City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Eshu Umbrellas")
			record.Put("RareSystem", "Eshu")
			record.Put("RareStation", "Shajn Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Esuseku Caviar")
			record.Put("RareSystem", "Esuseku")
			record.Put("RareStation", "Savinykh Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Ethgreze Tea Buds")
			record.Put("RareSystem", "Ethgreze")
			record.Put("RareStation", "Bloch Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Fujin Tea")
			record.Put("RareSystem", "Fujin")
			record.Put("RareStation", "Futen Spaceport")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Geawen Dance Dust")
			record.Put("RareSystem", "Geawen")
			record.Put("RareStation", "Obruchev Legacy")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Pantaa Prayer Sticks")
			record.Put("RareSystem", "George Pantazis")
			record.Put("RareStation", "Zakam Platform")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Goman Yaupon Coffee")
			record.Put("RareSystem", "Goman")
			record.Put("RareStation", "Gustav Sporer Port")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Haidne Black Brew")
			record.Put("RareSystem", "Haiden")
			record.Put("RareStation", "Searfoss Enterprise")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Havasupai Dream Catcher")
			record.Put("RareSystem", "Havasupai")
			record.Put("RareStation", "Lovelace Port")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Live Hecate Sea Worms")
			record.Put("RareSystem", "Hecate")
			record.Put("RareStation", "RJH1972")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Ceremonial Heike Tea")
			record.Put("RareSystem", "Heike")
			record.Put("RareStation", "Brunel City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Helvetitj Pearls")
			record.Put("RareSystem", "Helvetitj")
			record.Put("RareStation", "Friend Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Jaques Queintian Still")
			record.Put("RareSystem", "HIP 110620")
			record.Put("RareStation", "Jaques Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "HIP Prot")
			record.Put("RareSystem", "HIP 41181")
			record.Put("RareStation", "Andersson Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Burnham Bile Distillate")
			record.Put("RareSystem", "HIP 59533")
			record.Put("RareStation", "Burnham Beacon")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "HIP Organophospates")
			record.Put("RareSystem", "HIP 80364")
			record.Put("RareStation", "Stasheff Colony")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Holva Duelling Blades")
			record.Put("RareSystem", "Holva")
			record.Put("RareStation", "Kreutz Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "HR 7221 Wheat")
			record.Put("RareSystem", "HR 7221")
			record.Put("RareStation", "Veron City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Giant Irukama Snails")
			record.Put("RareSystem", "Irukama")
			record.Put("RareStation", "Blaauw City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Jaradharre Puzzle Box")
			record.Put("RareSystem", "Jaradharre")
			record.Put("RareStation", "Gohar Station")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Jaroua Rice")
			record.Put("RareSystem", "Jaroua")
			record.Put("RareStation", "Mccool City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Jotun Mookah")
			record.Put("RareSystem", "Jotun")
			record.Put("RareStation", "Icelock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Kachirigin Filter Leeches")
			record.Put("RareSystem", "Kachirigin")
			record.Put("RareStation", "Nowak Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Kamitra Cigars")
			record.Put("RareSystem", "Kamitra")
			record.Put("RareStation", "Hammel Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Kamorin Historic Weapons")
			record.Put("RareSystem", "Kamorin")
			record.Put("RareStation", "Godwin Vision")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Onion Head")
			record.Put("RareSystem", "Kappa Fornacis")
			record.Put("RareStation", "Harvestport")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Karetii Couture")
			record.Put("RareSystem", "Karetii")
			record.Put("RareStation", "Sinclair Platform")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Karsuki Locusts")
			record.Put("RareSystem", "Karsuki Ti")
			record.Put("RareStation", "West Market")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Kinago Violins")
			record.Put("RareSystem", "Kinago")
			record.Put("RareStation", "Fozard Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Kongga Ale")
			record.Put("RareSystem", "Kongga")
			record.Put("RareStation", "Laplace Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Koro Kung Pellets")
			record.Put("RareSystem", "Korro Kung")
			record.Put("RareStation", "Lonchakov Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Void Extract Coffee")
			record.Put("RareSystem", "LFT 1421")
			record.Put("RareStation", "Ehrlich Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Honesty Pills")
			record.Put("RareSystem", "LP 375-25")
			record.Put("RareStation", "King Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Mechucos High Tea")
			record.Put("RareSystem", "Mechucos")
			record.Put("RareStation", "Brandenstein Port")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Medb Starlube")
			record.Put("RareSystem", "Medb")
			record.Put("RareStation", "Vela Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Mokojing Beast Feast")
			record.Put("RareSystem", "Mokojing")
			record.Put("RareStation", "Noli Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Mukusubii Chiti")
			record.Put("RareSystem", "Mukusubii")
			record.Put("RareStation", "Ledyard Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Mulachi Giant Fungus")
			record.Put("RareSystem", "Mulachi")
			record.Put("RareStation", "Clark Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Neritus Berries")
			record.Put("RareSystem", "Neritus")
			record.Put("RareStation", "Toll Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Ngadandari Fire Opals")
			record.Put("RareSystem", "Ngadandari")
			record.Put("RareStation", "Consolmagno Horizons")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Nguna Modern Antiques")
			record.Put("RareSystem", "Nguna")
			record.Put("RareStation", "Biggle Hub")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Soontill Relics")
			record.Put("RareSystem", "Ngurii")
			record.Put("RareStation", "Cheranovsky City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Njangari Saddles")
			record.Put("RareSystem", "Njangari")
			record.Put("RareStation", "Lee Hub")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Ochoeng Chillies")
			record.Put("RareSystem", "Ochoeng")
			record.Put("RareStation", "Roddenberry Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Giant Verrix")
			record.Put("RareSystem", "Phiagre")
			record.Put("RareStation", "Greeboskis Outpost")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Albino Quechua Mammoth Meat")
			record.Put("RareSystem", "Quechua")
			record.Put("RareStation", "Crown Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Rajukru Mult")
			record.Put("RareSystem", "Rajukru")
			record.Put("RareStation", "Snyder Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Rapa Bao Snake Skins")
			record.Put("RareSystem", "Rapa Bao")
			record.Put("RareStation", "Flagg Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Rusani Old Smokey")
			record.Put("RareSystem", "Rusani")
			record.Put("RareStation", "Fernandes Market")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Sanuma Decorative Meat")
			record.Put("RareSystem", "Sanuma")
			record.Put("RareStation", "Dunyach Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Lucan Onion Head")
			record.Put("RareSystem", "Tanmark")
			record.Put("RareStation", "Cassie-L-Peia")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Terra Mater Blood Bores")
			record.Put("RareSystem", "Terra Mater")
			record.Put("RareStation", "Gr8minds")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Thrutis Cream")
			record.Put("RareSystem", "Thrutis")
			record.Put("RareStation", "Kingsbury Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Tiolce Waste 2 Paste")
			record.Put("RareSystem", "Tiolce")
			record.Put("RareStation", "Gordon Terminal")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Toxandji Virocide")
			record.Put("RareSystem", "Toxandji")
			record.Put("RareStation", "Tsunenaga Orbital")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Uszaian Tree Grub")
			record.Put("RareSystem", "Uszaa")
			record.Put("RareStation", "Guest Installation")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Utgaroar Millennial Eggs")
			record.Put("RareSystem", "Utgaroar")
			record.Put("RareStation", "Fort Klarix")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Uzumoku Lo")
			record.Put("RareSystem", "Uzumoku")
			record.Put("RareStation", "Sverdrup Ring")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Herculis Body Rub")
			record.Put("RareSystem", "V1090 Herculis")
			record.Put("RareStation", "Kaku Plant")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Vanayequi Ceratomorpha Fur")
			record.Put("RareSystem", "Vanayequi")
			record.Put("RareStation", "Clauss Hub")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Vega Slimweed")
			record.Put("RareSystem", "Vega")
			record.Put("RareStation", "Taylor City")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Vidavantian Lace")
			record.Put("RareSystem", "Vidavanta")
			record.Put("RareStation", "Lee Mines")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Volkhab Bee Drones")
			record.Put("RareSystem", "Volkhab")
			record.Put("RareStation", "Vernadsky Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Wheemete Wheat Cakes")
			record.Put("RareSystem", "Wheemete")
			record.Put("RareStation", "Eisinga Enterprise")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Wulpa Hyperbore Systems")
			record.Put("RareSystem", "Wulpa")
			record.Put("RareStation", "Williams Gateway")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Wuthielo Ku Froth")
			record.Put("RareSystem", "Wuthielo Ku")
			record.Put("RareStation", "Tarter Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Xihe Biomorphic Companions")
			record.Put("RareSystem", "Xihe")
			record.Put("RareStation", "Zhen Dock")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
			record.Put("RareDesc", "Yaso Kondi Leaf")
			record.Put("RareSystem", "Yaso Kondi")
			record.Put("RareStation", "Wheeler Market")
			record.Put("Allowance", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"RareCommodities",record)
		End If
	End If
End Sub

Sub StockTypesTable
	If SQLUtils.TableExists(Starter.SQLExec,"StockTypes") = False Then
		' Create Stock Type Table
		Q = "CREATE TABLE StockTypes(StockTypeDesc TEXT PRIMARY KEY)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Default Data Load
		Q = "SELECT * FROM StockTypes"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("StockTypeDesc", "Not Tradeable")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockTypes",record)
			record.Put("StockTypeDesc", "Demand")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockTypes",record)
			record.Put("StockTypeDesc", "Supply")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockTypes",record)
		End If
	End If
End Sub

Sub StockLevelsTable
	If SQLUtils.TableExists(Starter.SQLExec,"StockLevels") = False Then
		' Create Stock Level Table
		Q = "CREATE TABLE StockLevels(StockLevelDesc TEXT PRIMARY KEY, StockLevelRank INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Deafult Data Load
		Q = "SELECT * FROM StockLevels"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("StockLevelDesc", "High")
			record.Put("StockLevelRank", 4)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockLevels",record)
			record.Put("StockLevelDesc", "Medium")
			record.Put("StockLevelRank", 2)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockLevels",record)
			record.Put("StockLevelDesc", "Low")
			record.Put("StockLevelRank", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StockLevels",record)
		End If
	End If
End Sub

Sub GovernmentsTable
	If SQLUtils.TableExists(Starter.SQLExec,"Governments") = False Then
		' Create Government Table
		Q = "CREATE TABLE Governments(GovDesc TEXT PRIMARY KEY, NumOfEntries INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Default Data Load
		Q = "SELECT * FROM Governments"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("NumOfEntries", 0)
			
			record.Put("GovDesc","Anarchy")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Colony")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Corporate")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Communism")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Confederacy")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Cooperative")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Democracy")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Dictatorship")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Feudal")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Imperial")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Patronage")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Prison Colony")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
			record.Put("GovDesc","Theocracy")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Governments",record)
		End If
	End If
End Sub

Sub AllegianceTable
	If SQLUtils.TableExists(Starter.SQLExec,"Allegiance") = False Then
		' Create Allegiance Table
		Q = "CREATE TABLE Allegiance(AllegDesc TEXT PRIMARY KEY, NumOfEntries INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		Q = "SELECT * FROM Allegiance"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("NumOfEntries", 0)
			
			record.Put("AllegDesc","Alliance")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Allegiance",record)
			record.Put("AllegDesc","Anarchy")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Allegiance",record)
			record.Put("AllegDesc","Empire")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Allegiance",record)
			record.Put("AllegDesc","Federation")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Allegiance",record)
			record.Put("AllegDesc","Independent")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Allegiance",record)
		End If
	End If
End Sub

Sub EconomiesTable
	If SQLUtils.TableExists(Starter.SQLExec,"Economies") = False Then
		' Create Economy Table
		Q = "CREATE TABLE Economies(EconomyID INTEGER PRIMARY KEY, EconomyDesc TEXT, Surface INTEGER, NumOfEntries INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		Q = "SELECT * FROM Economies"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("NumOfEntries", 0)
			
			record.Put("EconomyID", 0)
			record.Put("EconomyDesc","NO MARKET")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 1)
			record.Put("EconomyDesc","Agriculture")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 2)
			record.Put("EconomyDesc","Agriculture (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 4)
			record.Put("EconomyDesc","Extraction")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 8)
			record.Put("EconomyDesc","Extraction (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 16)
			record.Put("EconomyDesc","High Tech")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 32)
			record.Put("EconomyDesc","High Tech (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 64)
			record.Put("EconomyDesc","Industrial")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 128)
			record.Put("EconomyDesc","Industrial (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 256)
			record.Put("EconomyDesc","Military")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 512)
			record.Put("EconomyDesc","Military (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 1024)
			record.Put("EconomyDesc","Refinery")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 2048)
			record.Put("EconomyDesc","Refinery (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 4096)
			record.Put("EconomyDesc","Service")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 8192)
			record.Put("EconomyDesc","Service (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 16384)
			record.Put("EconomyDesc","Terraforming")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 32768)
			record.Put("EconomyDesc","Terraforming (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 65536)
			record.Put("EconomyDesc","Tourism")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 131072)
			record.Put("EconomyDesc","Tourism (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 262144)
			record.Put("EconomyDesc","Mining Only")
			record.Put("Surface", 0)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
			record.Put("EconomyID", 524288)
			record.Put("EconomyDesc","Colony (Surf)")
			record.Put("Surface", 1)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Economies",record)
		End If
	End If
End Sub

Sub StationTypesTable
	If SQLUtils.TableExists(Starter.SQLExec,"StationTypes") = False Then
		' Create StationTypes Table
		Q = "CREATE TABLE StationTypes(StatTypeDesc TEXT PRIMARY KEY, NumOfStations INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		Q = "SELECT * FROM StationTypes"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("NumOfStations", 0)
			
			record.Put("StatTypeDesc","Coriolis")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
			record.Put("StatTypeDesc","Ocellus Station")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
			record.Put("StatTypeDesc","Orbis Starport")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
			record.Put("StatTypeDesc","Outpost")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
			record.Put("StatTypeDesc","Settlement")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
			record.Put("StatTypeDesc","Surface Port")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"StationTypes",record)
		End If
	End If
End Sub

Sub PopulationTable
	If SQLUtils.TableExists(Starter.SQLExec,"Population") = False Then
		'Create Population Table
		Q = "CREATE TABLE Population(PopDesc TEXT PRIMARY KEY)"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
End Sub

Sub LocationTable
	If SQLUtils.TableExists(Starter.SQLExec,"Location") = False Then
		' Create System Location Table
		Q = "CREATE TABLE Location(LocationID INTEGER PRIMARY KEY, SystemName TEXT, StationName TEXT)"
		Starter.SQLExec.ExecNonQuery(Q)
		Q = "SELECT * FROM Location"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("LocationID", 1)
			record.Put("SystemName", "SOL")
			record.Put("StationName", "Not Set")
			SQLUtils.Table_InsertMap(Starter.SQLExec,"Location",record)
		End If
	End If
End Sub

Sub MaxLYTradeDistanceTable
	If SQLUtils.TableExists(Starter.SQLExec,"MaxLYTradeDistance") = False Then
		' Create Max LY Trade Distance Table
		Q = "CREATE TABLE MaxLYTradeDistance(MaxLYID INTEGER PRIMARY KEY, TradeDistance INTEGER)"
		Starter.SQLExec.ExecNonQuery(Q)
		Q = "SELECT * FROM MaxLYTradeDistance"
		C = Starter.SQLExec.ExecQuery(Q)
		If C.RowCount = 0 Then
			record.Initialize
			record.Put("MaxLYID", 1)
			record.Put("TradeDistance", 250)
			SQLUtils.Table_InsertMap(Starter.SQLExec,"MaxLYTradeDistance",record)
		End If
	End If
End Sub

Sub TempTables
	If SQLUtils.TableExists(Starter.SQLExec,"TempStations") = False Then
		' Create TempStations Table
		Q = "CREATE TABLE TempStations(StationName TEXT PRIMARY KEY, SystemName TEXT, StatTypeDesc TEXT, PopulationSize TEXT, EconomyNum INTEGER, ECDesc TEXT, BlackMarketAvailable INTEGER, ArrivalPoint REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
	End If

	If SQLUtils.TableExists(Starter.SQLExec,"ReferenceSector") = False Then
		' Create ReferenceSector Table
		Q = "CREATE TABLE ReferenceSector(SectorName TEXT, AzimuthStartRad REAL, LatitudeStartRad REAL, WidthAngle REAL, Azimuth REAL, AzimuthCenter REAL, AzimuthCenterRad REAL, Latitude REAL, LatitudeCenter REAL, LatitudeCenterRad REAL, Width REAL, minWeight REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
	
	If SQLUtils.TableExists(Starter.SQLExec,"usedReferences") = False Then
		'Create usedReferences Table
		Q = "CREATE TABLE usedReferences(SectorName TEXT, SystemName TEXT, Weight REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"usedReferences","Sector","SectorName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"usedReferences","WeightRank","Weight",False)
	End If
		
	If SQLUtils.TableExists(Starter.SQLExec,"candidateReferences") = False Then
		' Create candidateReferences Table
		Q = "CREATE TABLE candidateReferences(SectorName TEXT, SystemName TEXT, Weight REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"candidateReferences","Sector","SectorName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"candidateReferences","WeightRank","Weight",False)
	End If
	
	If SQLUtils.TableExists(Starter.SQLExec,"optcandidateReferences") = False Then
		' Create optcandidateReferences Table
		Q = "CREATE TABLE optcandidateReferences(SectorName TEXT, SystemName TEXT, Weight REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
		' Create Indices
		SQLUtils.CreateIndex(Starter.SQLExec,"optcandidateReferences","Sector","SectorName",False)
		SQLUtils.CreateIndex(Starter.SQLExec,"optcandidateReferences","WeightRank","Weight",False)
	End If
	
	If SQLUtils.TableExists(Starter.SQLExec, "AnchorSystems") = False Then
		' Create AnchorSystems Table
		Q = "CREATE TABLE AnchorSystems(AnchorName TEXT, SpaceX REAL, SpaceY REAL, SpaceZ REAL, EnteredDistance REAL, Weight REAL)"
		Starter.SQLExec.ExecNonQuery(Q)
		SQLUtils.CreateIndex(Starter.SQLExec,"AnchorSystems","WeightRank","Weight",False)
	End If
End Sub

Sub SystemPlotTableDelete
	If SQLUtils.TableExists(Starter.SQLExec,"ReferenceSector") = True Then
		Q = "DROP TABLE ReferenceSector"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
	If SQLUtils.TableExists(Starter.SQLExec,"usedReferences") = True Then
		Q = "DROP TABLE usedReferences"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
	If SQLUtils.TableExists(Starter.SQLExec,"candidateReferences") = True Then
		Q = "DROP TABLE candidateReferences"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
	If SQLUtils.TableExists(Starter.SQLExec,"optcandidateReferences") = True Then
		Q = "DROP TABLE optcandidateReferences"
		Starter.SQLExec.ExecNonQuery(Q)
	End If
	If SQLUtils.TableExists(Starter.SQLExec,"AnchorSystems") = True Then
		Q = "DROP TABLE AnchorSystems"
		Starter.SQLExec.ExecNonQuery(Q)
	End If

End Sub